### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by andytriboletti** [takuaraki/DependenciesVersionChecker#13]
I'm running on Android Studio Beta 4 in the Canary channel and I just installed DependenciesVersionChecker.

I got an error after installing:
8:40:32 AM Plugin Error: Dependencies Version Checker threw an uncaught PluginException. Disable Plugin
8:40:32 AM PluginException: VersionCheckWindow : Unsupported major.minor version 52.0 [Plugin: io.github.takuaraki.dvc]
8:40:36 AM PluginException: VersionCheckWindow : Unsupported major.minor version 52.0 [Plugin: io.github.takuaraki.dvc]

**Comment by takuaraki** [comment]
@andytriboletti 
Thank you for reporting. Perhaps, this exception was thrown because I carelessly compiled my plugin by `jdk8` on my plugin version `1.2`.

Could you tell me your jdk version and my plugin version? I guess you use `jdk7` or `jdk6`.

**Comment by Lasse-Hansen** [comment]
I got the same problem. Using your plugin version 1.2, and my JDK version is 1.8.0_76

**Comment by takuaraki** [comment]
hmm..

I guess android studio is running on JRE6 regardless of developer's jdk version.
http://developer.android.com/sdk/index.html#Requirements

Therefore, I think #14 is still the solution of this issue.
I'll release v1.3 include #14 soon.
