### ISSUE TITLE
Can't find dependencies with format other than 'compile com.jakewharton:butterknife:7.0.0'

### ISSUE THREAD

**Issue by osrl** [takuaraki/DependenciesVersionChecker#5]
Only finds one kind of dependency which is 'compile com.jakewharton:butterknife:7.0.0'. Can't find different types like:

```
def okhttpVersion = '2.7.0'
compile "com.squareup.okhttp:okhttp:$okhttpVersion"
compile("com.squareup.retrofit:retrofit:2.0.0-beta2") {
    exclude group: 'com.squareup.okhttp'
}
```

**Comment by furyu-araki** [comment]
@osrl 
Thank you for reporting this issue. As you pointed out, this plugin can extract only 'groupId:artifactId:version'.
I will improve my plugin to extract much more patterns.

**Comment by takuaraki** [comment]
@osrl 
Thank you for reporting this issue. As you pointed out, this plugin can extract only 'groupId:artifactId:version'.
I will improve my plugin to extract much more patterns.

**Comment by takuaraki** [comment]
It's difficult for me to immediately adapt injection of defined value like:

```
def okhttpVersion = '2.7.0'
compile "com.squareup.okhttp:okhttp:$okhttpVersion"
```

Then, I close this issue by extracting:

```
compile("com.squareup.retrofit:retrofit:2.0.0-beta2") {
    exclude group: 'com.squareup.okhttp'
}
```

**Comment by osrl** [comment]
Why don't you try to replace $okhttpVersion with '2.7.0'. I don't think it's that difficult. You are manuplating the script as a string right?

**Comment by ben-manes** [comment]
Perhaps instead you could use Gradle to resolve the latest dependencies? This is what I do in my [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin).

You could probably take the user's `build.gradle`, rewrite it to include my plugin, call that new script using either `gradle --build-file ...` or via the `GradleConnector`, and obtain the results as a json output. Then parse and display accordingly. That way you let Gradle do the heavy lifting and don't try to reinvent its dependency management.

**Comment by takuaraki** [comment]
@ben-manes 
Thank you for your advice.

> Perhaps instead you could use Gradle to resolve the latest dependencies? 

Yes. I feel hard for extracting build.gradle by my own programs. So I want to leave it to Gradle.

> You could probably take the user's `build.gradle`, rewrite it to include my plugin, call that new script using either `gradle --build-file ...` or via the `GradleConnector`, and obtain the results as a json output. Then parse and display accordingly.

This seems to be a good solution.

> call that new script using either `gradle --build-file ...` or via the `GradleConnector`

However, I cannot completely understand this sentence. I don't know how to call the script using either `gradle --build-file ...` or via the `GradleConnector` on my programs.
It probably takes much time for me to apply your solution, but I'll try it!!

**Comment by ben-manes** [comment]
It looks like you can do it much cleaner than my hack of rewriting a build script idea. If you use the [Gradle Tooling API](https://docs.gradle.org/current/javadoc/org/gradle/tooling/package-summary.html) and can find a way to get into the `GradleBuild`, you can get the list of all projects and run tasks against them. You can't extract the configuration directly, but you could run the `dependencies` task and pipe the output. Then you could parse the top-level list to get the dependencies, and away you go.

That still seems messier than it should be, so there is probably an API path that I'm missing. But it does appear that you can get the information from Gradle and then process it however you prefer.

**Comment by takuaraki** [comment]
@ben-manes 
Thanks a lot for your advice!!

I succeed to run some gradle tasks (`build`, `dependencyUpdates -DoutputFormatter=json`) by [GradleConnector](https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html).

As you say, I may get configuration by `dependencies` task if I can extract the output like:

```
compile - Compile classpath for source set 'main'.
+--- io.reactivex:rxjava:1.1.0
+--- io.reactivex:rxswing:0.24.0
|    \--- io.reactivex:rxjava:1.0.10 -> 1.1.0
\--- com.jetbrains:ideaIC:15.0.2
...
```

Now I have two method to resolve the Issue:
- rewrite users' build.gradle file -> run `dependencyUpdates` -> parse the json output -> display
- run `dependencies` -> extract the output (perhaps I can get only using versions) -> get latest versions -> display

I'll try the both (and another method if exists), and adopt the one I prefer.

**Comment by osrl** [comment]
I don't know if you should bother anymore, it's your decision but check this [SO answer](http://stackoverflow.com/a/35371234/1120126). Android Studio team is implementing this.

**Comment by ben-manes** [comment]
That looks really cool =)

You may want to check if the user't build file uses the [new plugin syntax](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block). I think that will fail if both it and a `buildscript` block are defined, which is pretty annoying.
