### ISSUE TITLE
Cannot find latest version of fablic libraries

### ISSUE THREAD

**Issue by takuaraki** [takuaraki/DependenciesVersionChecker#6]
## Problem

This plugin only refer to `http://repo1.maven.org/maven2/...`.
## Solution

Refer to `http://twittersdk.artifactoryonline.com/twittersdk/public/...` too.

**Comment by Dev-iL** [comment]
Also [jCenter](https://jcenter.bintray.com/) please... :)

**Comment by takuaraki** [comment]
@Dev-iL 
I will solve this issue and your demand( [jCenter](https://jcenter.bintray.com/) Support ) by solving #9.
